Ported and packaged High Performance Cars sample (Gianluca) to JRS 5.6 - Need to fix the JAR functions   2014-06-25 15:59:43,730 ERROR SystemErrorController,TP-Processor7:61 -   Internal server error
  org.springframework.web.util.NestedServletException: Handler
  processing failed; nested exception is
  java.lang.UnsupportedClassVersionError: test/man/ManFunctions :
  Unsupported major.minor version 51.0 (unable to load class
  test.man.ManFunctions)

  Caused by: java.lang.UnsupportedClassVersionError:
  test/man/ManFunctions : Unsupported major.minor version 51.0 (unable
  to load class test.man.ManFunctions)

- Need to recreate the organization structure manually to have the 5.6
  default themes, then to import the current export without update, then
  to re-create the export with all the default themes updated